remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigtion:
  - name: Readme
    link: ./index.html
  - name: Jupter Notebook Model Code 
    link: ./housing_price_predictor.html
